language: ruby
rvm:
  - 2.7
before_install:
  - gem install bundler
script:
  - bundle exec jekyll build
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
cache: bundler
