language: ruby
rvm:
  - 2.0.0
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --url-ignore /linkedin\.com/
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
cache: bundler
