# Dependencies
markdown:         kramdown
highlighter:      rouge

# kramdown settings
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Joel S. Miller
tagline:          'Amassed Ramblings'
description:      'I am an Engineering Manager at <a href="https://www.tumblr.com" target="_blank">Tumblr</a> where I lead a team which builds <a href="https://en.wikipedia.org/wiki/Scalability" target="_blank">scalable</a> and <a href="https://en.wikipedia.org/wiki/Distributed_computing" target="_blank">distributed</a> infrastructure using <a href="https://en.wikipedia.org/wiki/List_of_free_and_open-source_software_packages" target="_blank">open-source technologies</a>.'

url:              http://www.joelsmiller.com
baseurl:          /

author:
  name:           'Joel S. Miller'
  url:            https://twitter.com/esquireofoz

github:
  handle:         https://github.com/esquireofoz

twitter:
  handle:         https://twitter.com/esquireofoz

linkedin:
  handle:         https://linkedin.com/in/joelsmiller

stackexchange:
  handle:         http://stackexchange.com/users/1067146/esquireofoz?tab=accounts

exclude:          [vendor]

paginate:         5
