# Dependencies
markdown:         kramdown
highlighter:      rouge

# kramdown settings
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Joel S. Miller
tagline:          'Amassed Ramblings'
description:      'I manage the Perimeter Team at <a href="https://www.tumblr.com" target="_blank">Tumblr</a> where I build scalable infrastructure using <a href="https://twitter.com/puppetlabs" target="_blank">Puppet</a>, <a href="https://www.ruby-lang.org/en/" target="_blank">Ruby</a>, <a href="https://www.nginx.com/" target="_blank">nginx</a>, <a href="https://varnish-cache.org/" target="_blank">varnish</a> and a plethora of <a href="https://en.wikipedia.org/wiki/List_of_free_and_open-source_software_packages" target="_blank">other technologies</a>.'

url:              http://www.joelsmiller.com
baseurl:          /

author:
  name:           'Joel S. Miller'
  url:            https://twitter.com/esquireofoz

github:
  handle:         https://github.com/esquireofoz

twitter:
  handle:         https://twitter.com/esquireofoz

linkedin:
  handle:         https://linkedin.com/in/joelsmiller

stackexchange:
  handle:         http://stackexchange.com/users/1067146/esquireofoz?tab=accounts

exclude:          [vendor]

paginate:         5
